import{a as v,S as w,i as l}from"./assets/vendor-CucEYOFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();async function f(s,r){return(await v.get("https://pixabay.com/api/",{params:{key:"56427454-39c521709c23a9b65e6fd603c",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const i={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")},b=new w(".gallery a");function m(s){const r=s.map(e=>`<li>
  <a href="${e.largeImageURL}">
    <img src="${e.webformatURL}" alt="${e.tags}" />
  </a>
  <div>
    <p>Likes: ${e.likes}</p>
    <p>Views: ${e.views}</p>
    <p>Comments: ${e.comments}</p>
    <p>Downloads: ${e.downloads}</p>
  </div>
</li>
  `).join("");i.gallery.insertAdjacentHTML("beforeend",r),b.refresh()}function S(){i.gallery.innerHTML=""}function y(){i.loader.classList.add("is-visible")}function h(){i.loader.classList.remove("is-visible")}function p(){i.loadMoreBtn.classList.add("is-visible")}function g(){i.loadMoreBtn.classList.remove("is-visible")}const u={form:document.querySelector(".form"),inputData:document.querySelector('input[name="search-text"]'),loadMoreBtn:document.querySelector(".load-more")};let L="",n=1,c=0;u.form.addEventListener("submit",M);u.loadMoreBtn.addEventListener("click",q);async function M(s){s.preventDefault();const r=u.form.elements["search-text"].value.trim();if(r){L=r,n=1,c=0,S(),g(),y();try{const e=await f(r,n),a=e.hits;if(c=Math.ceil(e.totalHits/15),!a.length){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}m(a),n<c&&p()}catch{l.error({message:"Something went wrong. Please try again!"})}finally{h()}}}async function q(){n+=1,g(),y();try{const r=(await f(L,n)).hits;if(!r.length){l.info({message:"We're sorry, but you've reached the end of search results."});return}m(r);const e=document.querySelector(".gallery li");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}n<c?p():l.info({message:"We're sorry, but you've reached the end of search results."})}catch{l.error({message:"Something went wrong. Please try again!"})}finally{h()}}
//# sourceMappingURL=index.js.map
