import{a as v,S as b,i as n}from"./assets/vendor-CucEYOFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();async function m(s,r){return(await v.get("https://pixabay.com/api/",{params:{key:"56427454-39c521709c23a9b65e6fd603c",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const l={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")},w=new b(".gallery a");function y(s){const r=s.map(e=>`<li>
  <a href="${e.largeImageURL}">
    <img src="${e.webformatURL}" alt="${e.tags}" />
  </a>
  <div>
    <p>Likes: ${e.likes}</p>
    <p>Views: ${e.views}</p>
    <p>Comments: ${e.comments}</p>
    <p>Downloads: ${e.downloads}</p>
  </div>
</li>
  `).join("");l.gallery.insertAdjacentHTML("beforeend",r),w.refresh()}function S(){l.gallery.innerHTML=""}function h(){l.loader.classList.add("is-visible")}function g(){l.loader.classList.remove("is-visible")}function p(){l.loadMoreBtn.classList.add("is-visible")}function u(){l.loadMoreBtn.classList.remove("is-visible")}const f={form:document.querySelector(".form"),inputData:document.querySelector('input[name="search-text"]'),loadMoreBtn:document.querySelector(".load-more")};let L="",i=1,c=0;f.form.addEventListener("submit",M);f.loadMoreBtn.addEventListener("click",q);async function M(s){s.preventDefault();const r=f.form.elements["search-text"].value.trim();if(r){L=r,i=1,c=0,S(),u(),h();try{const e=await m(r,i),a=e.hits;if(c=Math.ceil(e.totalHits/15),!a.length){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(a),i<c?p():(u(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Something went wrong. Please try again!"})}finally{g()}}}async function q(){i+=1,u(),h();try{const r=(await m(L,i)).hits;if(!r.length){n.info({message:"We're sorry, but you've reached the end of search results."});return}y(r);const e=document.querySelector(".gallery li");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}i<c?p():n.info({message:"We're sorry, but you've reached the end of search results."})}catch{n.error({message:"Something went wrong. Please try again!"})}finally{g()}}
//# sourceMappingURL=index.js.map
