import{a as g,S as p,i as n}from"./assets/vendor-CucEYOFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();async function d(s,r){return(await g.get("https://pixabay.com/api/",{params:{key:"56427454-39c521709c23a9b65e6fd603c",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const c={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")},v=new p(".gallery a");function f(s){const r=s.map(t=>`<li>
  <a href="${t.largeImageURL}">
    <img src="${t.webformatURL}" alt="${t.tags}" />
  </a>
  <div>
    <p>Likes: ${t.likes}</p>
    <p>Views: ${t.views}</p>
    <p>Comments: ${t.comments}</p>
    <p>Downloads: ${t.downloads}</p>
  </div>
</li>
  `).join("");c.gallery.insertAdjacentHTML("beforeend",r),v.refresh()}function L(){c.gallery.innerHTML=""}function m(){c.loader.classList.add("is-visible")}function y(){c.loader.classList.remove("is-visible")}const i={form:document.querySelector(".form"),inputData:document.querySelector('input[name="search-text"]'),loadMoreBtn:document.querySelector(".load-more")};let h="",l=1;i.form.addEventListener("submit",b);i.loadMoreBtn.addEventListener("click",w);async function b(s){s.preventDefault();const r=i.form.elements["search-text"].value.trim();if(r){h=r,l=1,L(),i.loadMoreBtn.classList.remove("is-visible"),m();try{const t=await d(r,l),a=t.hits,e=Math.ceil(t.totalHits/15);if(!a.length){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}f(a),e>1?i.loadMoreBtn.classList.add("is-visible"):n.info({message:"We're sorry, but you've reached the end of search results."})}catch{n.error({message:"Something went wrong. Please try again!"})}finally{y()}}}async function w(){l+=1,m();try{const s=await d(h,l),r=s.hits,t=Math.ceil(s.totalHits/15);if(!r.length){i.loadMoreBtn.classList.remove("is-visible"),n.info({message:"We're sorry, but you've reached the end of search results."});return}f(r);const a=document.querySelector(".gallery li");if(a){const e=a.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}l>=t&&(i.loadMoreBtn.classList.remove("is-visible"),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Something went wrong. Please try again!"})}finally{y()}}
//# sourceMappingURL=index.js.map
